# Generated by Django 3.2.12 on 2022-02-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(blank=True, upload_to="users/%Y/%m/%d/"),
        ),
        migrations.AlterModelTable(
            name="image",
            table=None,
        ),
    ]
