# Generated by Django 3.2.12 on 2022-02-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0005_auto_20220223_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='users/'),
        ),
    ]
