# Generated by Django 3.2.12 on 2022-03-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0014_prediction_predicted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='imagine',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='result',
            name='prediction_feedback',
        ),
    ]
